export const items = [
  'Bacon',
  'BBQ Chicken',
  'Black Olives',
  'Bosco Sticks',
  'Bottled Beverages',
  'Buffalo Chicken',
  'Canadian Bacon',
  'Cheese Quesadilla (Half / Whole)',
  'Chicken Bacon Ranch',
  'Chicken Pesto',
  'Chicken Strips',
  'Chicken',
  'Chips & Salsa',
  'Fountain Drinks',
  'Garden Pita',
  'Garlic Cheesy Bread',
  'Green Peppers',
  'Ice Cream',
  'Jalapeños',
  'Large Pizza (16 in)',
  'M&Ms',
  'Mushrooms',
  'Nachos',
  'Ole Pizza',
  'Onions',
  'Oreo',
  'Pause Cookie',
  'Pepperoni',
  'Pineapple',
  'Pita Pizza',
  'Pizza Bagel - Specialty',
  'Pizza Bagel',
  'Reese’s peanut butter cups',
  'Root Beer Float',
  'Sausage',
  'Shakes',
  'Side of Sauce',
  'Slice',
  'Small Pizza (12 in)',
  'Soft Pretzel',
  'Specialty Pita Pizza',
  'Spinach',
  'Toasted Pita and Hummus',
  'Tomatoes',
  'Ultimate Quesadilla (Half / Whole)',
]
